# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckKRbhkRy74tgO51dX2CYXvTf1qrkggA
"""

pip install PyPDF2 sentence-transformers faiss-cpu transformers torch

from google.colab import drive
drive.mount('/content/drive')

from PyPDF2 import PdfReader

def extract_text_from_pdf(pdf_path):
  reader = PdfReader(pdf_path)
  text = ""
  for page in reader.pages:
    if page.extract_text():
      text += page.extract_text()
  return text

def split_into_chunks(text, chunk_size=300):
  words = text.split()
  chunks = [" ".join(words[i:i+chunk_size]) for i in range(0, len(words), chunk_size)]
  return chunks

from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

embedder = SentenceTransformer('all-MiniLM-L6-v2')

def create_faiss_index(chunks):
  embeddings = embedder.encode(chunks)
  dim = embeddings.shape[1]
  index = faiss.IndexFlatL2(dim)
  index.add(np.array(embeddings))
  return index, embeddings

def get_top_chunks(question, chunks, index, embeddings, top_k=2):
  q_emb = embedder.encode([question])
  distances, indices = index.search(q_emb, top_k)
  results = [chunks[i] for i in indices[0]]
  return " ".join(results)

from transformers import pipeline

qa_model = pipeline("question-answering", model="distilbert-base-cased-distilled-squad")

def ask_pdf_question(pdf_path, question):
  text = extract_text_from_pdf(pdf_path)
  chunks = split_into_chunks(text)
  index, embeddings = create_faiss_index(chunks)
  context = get_top_chunks(question, chunks, index, embeddings)

  result = qa_model(question=question, context=context)
  return result["answer"]

pdf_path = "/content/Friend_Personality_Description.pdf"
question = "What is the main topic discussed in this document?"

answer = ask_pdf_question(pdf_path, question)
print("Answer:", answer)

question = "how to find if my friend is introvert or not"
answer = ask_pdf_question(pdf_path, question)
print("Answer:", answer)

pdf_path = "/content/Friend_Personality_Description.pdf"
question = "What is personality?"

answer = ask_pdf_question(pdf_path, question)
print("Answer:", answer)

pdf_path = "/content/Friend_Personality_Description.pdf"
question = "Example Paragraph on a Friend’s Personality"

answer = ask_pdf_question(pdf_path, question)
print("Answer:", answer)